### ISSUE TITLE
Fix failing unit test DiffRowGeneratorTest#testGenerator_InlineDiff

### ISSUE THREAD

**Issue by j2gl** [j2gl/java-diff-utils#1]
There is a unit test failing:

```
java.lang.ArrayIndexOutOfBoundsException: 1

    at difflib.DiffRowGenerator.copyEqualsLines(DiffRowGenerator.java:418)
    at difflib.DiffRowGenerator.generateDiffRows(DiffRowGenerator.java:387)
    at difflib.DiffRowGenerator.generateDiffRows(DiffRowGenerator.java:281)
    at diffutils.DiffRowGeneratorTest.testGenerator_InlineDiff(DiffRowGeneratorTest.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

[EQUAL,anything,anything]
[EQUAL,,]
[EQUAL,other,other]
[CHANGE,more lines,some more lines]
[CHANGE,anything ,anything]
[CHANGE, ,]
[EQUAL,other,other]
```

**Comment by j2gl** [comment]
Bug fixed.
